import re

PLUGIN_VERSION = "1.5.3"
PLUGIN_RELEASE_NAME = "Debug Scope Hotfix"

# Mnemosyne 长期记忆插件将通过动态方式调用
MNEMOSYNE_MAX_SHARED_MEMORIES = 200
DEBUG_FOOTER_PATTERN = re.compile(r"(?:\n\s*)?---\n\*\[好感:[\s\S]*$", re.DOTALL)
JSON_FENCE_OPEN_PATTERN = re.compile(r"^```(?:json)?\s*")
JSON_FENCE_CLOSE_PATTERN = re.compile(r"\s*```$")
JSON_OBJECT_PATTERN = re.compile(r"\{[\s\S]*\}")
WHITESPACE_PATTERN = re.compile(r"\s+")
BRACKETED_MEMORY_PREFIX_PATTERN = re.compile(r"^\[(?:[^\]]+/[^\]]+|[^\]]+·[^\]]+)\]\s*")
AUTO_SUMMARY_PREFIX_PATTERN = re.compile(r"^自动总结[:：]\s*")
QUOTE_PATTERN = re.compile(r"[“”\"'`]")
CN_EN_PUNCT_PATTERN = re.compile(r"[，。！？；：,.!?;:]+")
ASCII_TERM_PATTERN = re.compile(r"[a-z0-9]{2,}")
CJK_TERM_PATTERN = re.compile(r"[\u4e00-\u9fff]{2,}")
PERSONAL_MEMORY_CUE_PATTERN = re.compile(
    r"记住|记得|别忘|生日|喜欢|讨厌|害怕|秘密|承诺|答应|约定|以后|永远|只告诉|"
    r"不要|别这样|边界|对不起|抱歉|谢谢|陪我|离开|回来|只有你|唯一|"
    r"我叫|我是|叫我|称呼|职业|工作|学校|住在|来自|年龄|星座|家人|朋友"
)
PROFILE_UPDATE_CUE_PATTERN = re.compile(
    r"记住|记得|别忘|生日|喜欢吃|喜欢听|喜欢看|爱吃|爱听|爱看|不喜欢|讨厌|害怕|"
    r"秘密|承诺|答应|约定|只告诉|边界|"
    r"我叫|我是|叫我|称呼|职业|工作|学校|住在|来自|年龄|星座|家人|朋友"
)
CJK_ALNUM_PATTERN = re.compile(r"[A-Za-z0-9\u4e00-\u9fff]")
EMOTIVE_SYMBOL_PATTERN = re.compile(r"[❤♥💕💖💗💘💞💓😭😢😡😠😔🥺😘😳😞😟😥😰]")
LOW_VALUE_ACK_PATTERN = re.compile(
    r"^(嗯+|哦+|噢+|喔+|好+|行+|可以|ok|收到|知道了?|明白|了解|在|在吗|"
    r"你好|hello|hi|哈+|哈哈+|233+)$",
    re.IGNORECASE,
)
ANALYSIS_IMPORTANT_SIGNAL_PATTERN = re.compile(
    r"爱你|想你|抱抱|亲|喜欢|讨厌|对不起|抱歉|谢谢|离开|回来|晚安|秘密|承诺|"
    r"答应|约定|边界|唯一|命定|不要|别|滚|恶心|烦|羞辱|陪我"
)
ANALYSIS_MEMORY_ANCHOR_PATTERN = re.compile(
    r"又|再|还|刚才|刚刚|以前|之前|上次|那次|记得|忘|承诺|答应|约定|秘密|"
    r"边界|老样子|还是|别人|其他人|朋友|同事|前任|他说|她说|他们|她们"
)
LOCAL_ANALYSIS_SIMPLE_PATTERN = re.compile(
    r"谢谢|辛苦|真好|温柔|漂亮|可爱|厉害|喜欢你|喜欢妳|爱你|想你|抱抱|亲亲|晚安|再见|"
    r"对不起|抱歉|错了|原谅|滚|恶心|烦|讨厌|闭嘴|羞辱|亲身经历|亲眼|亲自|出去看看|"
    r"去看看|走出去|尝试|试着|或许你可以|你可以试试|值得一看|会不一样|比不上"
)
LOCAL_PROFILE_NAME_PATTERN = re.compile(
    r"(?:请)?(?:叫我|喊我|称呼我为|称呼我|我的名字是|我叫)\s*([A-Za-z0-9_\-\u4e00-\u9fff]{1,20})"
)
LOCAL_PROFILE_BIRTHDAY_PATTERN = re.compile(
    r"(?:我的生日是|我生日是|生日是|我生日)\s*([^，。！？,.!?]{2,30})"
)
LOCAL_PROFILE_JOB_PATTERN = re.compile(
    r"(?:我的职业是|职业是|我的工作是|工作是|我从事)\s*([^，。！？,.!?]{2,30})"
)
LOCAL_PROFILE_LOCATION_PATTERN = re.compile(
    r"(?:我来自|来自|我住在|住在)\s*([^，。！？,.!?]{2,30})"
)
LOCAL_PROFILE_LIKE_PATTERN = re.compile(
    r"(?:我)?(?:最喜欢|喜欢吃|喜欢听|喜欢看|爱吃|爱听|爱看|喜欢|爱)\s*([^，。！？,.!?]{1,40})"
)
LOCAL_PROFILE_DISLIKE_PATTERN = re.compile(
    r"(?:我)?(?:不喜欢|讨厌|反感|害怕)\s*([^，。！？,.!?]{1,40})"
)
PROFILE_ITEM_SPLIT_PATTERN = re.compile(r"[、,，/]+|以及|还有|和")
PROFILE_FOOD_HINT_PATTERN = re.compile(r"吃|喝|菜|饭|面|甜点|蛋糕|咖啡|茶|奶茶|火锅|烧烤|料理|食物")
PROFILE_MUSIC_HINT_PATTERN = re.compile(r"音乐|歌|歌曲|歌手|乐队|专辑|唱片|旋律")
PROFILE_BOOK_HINT_PATTERN = re.compile(r"书|小说|漫画|作者|文学|诗")
PROFILE_COLOR_PATTERN = re.compile(
    r"红色|蓝色|绿色|黄色|紫色|粉色|白色|黑色|灰色|橙色|金色|银色|青色|"
    r"红|蓝|绿|黄|紫|粉|白|黑|灰|橙|金|银|青"
)
PENDING_CACHE_TTL_SECONDS = 10 * 60
MESSAGE_CACHE_KEY_HASH_CHARS = 12
SAVE_DEBOUNCE_SECONDS = 1.0
DYNAMIC_PROMPT_CACHE_MAX_ENTRIES = 128
MNEMOSYNE_QUERY_CACHE_TTL_SECONDS = 60
MNEMOSYNE_QUERY_CACHE_MAX_ENTRIES = 256
LOCAL_MEMORY_QUERY_CACHE_TTL_SECONDS = 60
LOCAL_MEMORY_QUERY_CACHE_MAX_ENTRIES = 256
RECENT_HISTORY_CACHE_MAX_ENTRIES = 256
LOCAL_MEMORY_SCHEMA_VERSION = 2
MEMORY_MODE_PRESET = "balanced"
MEMORY_MODE_PRESETS = {"lean", "balanced", "rich"}
ENABLE_SCENE_MEMORY_MODE = True
PRIVATE_CHAT_MEMORY_MODE_PRESET = "rich"
GROUP_CHAT_MEMORY_MODE_PRESET = "lean"
PRIVATE_CHAT_CONTEXT_INJECTION = True
GROUP_CHAT_CONTEXT_INJECTION = False
PRIVATE_CHAT_INJECT_SUMMARY_AS_CONTEXT = True
GROUP_CHAT_INJECT_SUMMARY_AS_CONTEXT = False
ENABLE_ADAPTIVE_LIGHTWEIGHT_PROMPT = True
ADAPTIVE_LIGHTWEIGHT_PROMPT_MAX_CHARS = 36
ENABLE_PROMPT_BUDGET_GUARD = True
PROMPT_TOKEN_BUDGET = 2200
ENABLE_PROMPT_BUDGET_MEMORY_ANCHOR = True
PROMPT_BUDGET_MEMORY_ANCHOR_CHARS = 160
PROMPT_BUDGET_HISTORY_LIMIT = 12
ENABLE_PROMPT_BUDGET_AUTO_THROTTLE = True
PROMPT_BUDGET_AUTO_THROTTLE_MIN_STREAK = 2
PROMPT_BUDGET_AUTO_THROTTLE_RECOVERY_TURNS = 2
ENABLE_PROMPT_BUDGET_COMPRESSION_TIERS = True
PROMPT_BUDGET_HEAVY_COMPACT_STREAK = 5
PROMPT_BUDGET_THROTTLE_LOG_LIMIT = 8
PROMPT_BUDGET_THROTTLE_ESCALATION_HITS = 3
PROMPT_BUDGET_THROTTLE_ESCALATION_RECOVERY_CLEAR = 1
ENABLE_PROMPT_COST_PROFILE_STATS = True
PROMPT_COST_PROFILE_WINDOW = 20
ENABLE_PROMPT_COST_AUTO_MEMORY_MODE = True
PROMPT_COST_AUTO_LEAN_HIT_RATE = 45
PROMPT_COST_AUTO_BALANCED_HIT_RATE = 20
PROMPT_COST_AUTO_MODE_STICKY_TURNS = 2
ENABLE_PROMPT_BUDGET_MEMORY_MODE_ADAPTATION = True
PROMPT_BUDGET_MEMORY_MODE_PRESSURE_HIT_RATE = 34
PROMPT_BUDGET_MEMORY_MODE_LEAN_LIMIT = 1
PROMPT_BUDGET_MEMORY_MODE_BALANCED_LIMIT = 2
PROMPT_BUDGET_MEMORY_MODE_RICH_LIMIT = 3
PROMPT_BUDGET_MEMORY_MODE_LEAN_CHARS = 120
PROMPT_BUDGET_MEMORY_MODE_BALANCED_CHARS = 180
PROMPT_BUDGET_MEMORY_MODE_RICH_CHARS = 260
ENABLE_PROMPT_BUDGET_MEMORY_VALUE_PRIORITY = True
PROMPT_BUDGET_MEMORY_PRIORITY_CHAR_TRIGGER = 260
ENABLE_PROMPT_BUDGET_MEMORY_CANDIDATE_EXPANSION = True
PROMPT_BUDGET_MEMORY_CANDIDATE_MULTIPLIER = 3
PROMPT_BUDGET_MEMORY_CANDIDATE_MAX = 12
ENABLE_PROMPT_MEMORY_SLOT_DEDUP = True
ENABLE_PROMPT_MEMORY_SELECTION_TRACE = True
PROMPT_MEMORY_SELECTION_TRACE_LIMIT = 3
BACKGROUND_TASK_CONCURRENCY = 8
PERF_STATS_MAX_SAMPLES = 100
MNEMOSYNE_WRITE_DEBOUNCE_SECONDS = 0.35
HISTORY_COMPACT_INTERVAL = 50
HISTORY_DUPLICATE_WINDOW_SECONDS = 5
HISTORY_TAIL_BLOCK_SIZE = 8192
HISTORY_MAX_ENTRY_CHARS = 4000
PROFILE_UPDATE_INTERVAL_TURNS = 8
PROFILE_UPDATE_MIN_CHARS = 12
PROFILE_ANALYSIS_MAX_CHARS_PER_SIDE = 500
MEMORY_PROMPT_LIMIT = 5
MEMORY_PROMPT_EVENT_LIMIT = 2
MEMORY_PROMPT_IMPRESSION_LIMIT = 2
MEMORY_PROMPT_SUMMARY_LIMIT = 1
MEMORY_PROMPT_PROFILE_LIMIT = 1
INTERACTION_MEMORY_MIN_DELTA = 2
ENABLE_MEMORY_WRITE_CANDIDATES = True
MEMORY_WRITE_CANDIDATE_PROMOTE_HITS = 2
MEMORY_WRITE_CANDIDATE_LIMIT = 8
MEMORY_DECAY_DAYS = 45
MEMORY_HARD_CLEANUP_DAYS = 180
ENABLE_BUILTIN_MEMORY = True
BUILTIN_MEMORY_RETENTION_LIMIT = 1200
BUILTIN_MEMORY_PROMPT_CHAR_BUDGET = 260
BUILTIN_MEMORY_SUMMARY_MAX_CHARS = 90
BUILTIN_MEMORY_IMPORT_MAX_CONTENT_CHARS = 1200
BUILTIN_MEMORY_IMPORT_MAX_LINE_CHARS = 50000
ENABLE_TOKEN_COST_OPTIMIZATION = True
AVOID_DUPLICATE_CONTEXT_INJECTION = True
TOKEN_OPT_MEMORY_PROMPT_LIMIT = 3
TOKEN_OPT_CONTEXT_HISTORY_LIMIT = 6
TOKEN_OPT_CONTEXT_MAX_CHARS_PER_MSG = 220
TOKEN_OPT_ANALYSIS_HISTORY_LIMIT = 32
TOKEN_OPT_ANALYSIS_RELEVANT_MEMORY_LIMIT = 8
TOKEN_OPT_ANALYSIS_RECENT_CONTEXT_LIMIT = 4
TOKEN_OPT_ANALYSIS_MNEMOSYNE_MEMORY_LIMIT = 3
TOKEN_OPT_ANALYSIS_MAX_CHARS_PER_MSG = 600
TOKEN_OPT_ANALYSIS_CONTEXT_CHAR_BUDGET = 6_000
LOCAL_ANALYSIS_MAX_CHARS = 16
ANALYSIS_HISTORY_LIMIT = TOKEN_OPT_ANALYSIS_HISTORY_LIMIT
ANALYSIS_RELEVANT_MEMORY_LIMIT = TOKEN_OPT_ANALYSIS_RELEVANT_MEMORY_LIMIT
ANALYSIS_RECENT_CONTEXT_LIMIT = TOKEN_OPT_ANALYSIS_RECENT_CONTEXT_LIMIT
ANALYSIS_MNEMOSYNE_MEMORY_LIMIT = TOKEN_OPT_ANALYSIS_MNEMOSYNE_MEMORY_LIMIT
ANALYSIS_MAX_CHARS_PER_MSG = TOKEN_OPT_ANALYSIS_MAX_CHARS_PER_MSG
ANALYSIS_CONTEXT_CHAR_BUDGET = TOKEN_OPT_ANALYSIS_CONTEXT_CHAR_BUDGET
CONVERSATION_HISTORY_RETENTION_LIMIT = 1000
ACTIVE_EVENT_COOLDOWN_TURNS = 7
ACTIVE_EVENT_IDLE_HOURS = 24
NON_DESTINED_FAVOR_CAP = 55
ENABLE_CODE_STATE_DECISION = True
ENABLE_MEMORY_EVIDENCE_STAGE_GATE = True
ENABLE_PERSONA_CONSISTENCY_GUARD = True
ENABLE_REPLY_LENGTH_STRATEGY = True
ENABLE_PROMPT_TEMPLATE_MODE = True
ENABLE_ACTIVE_EVENT_QUEUE = True
ENABLE_STATE_EXPLANATION_LOG = True
ENABLE_MEMORY_EVIDENCE_GRADING = True
ENABLE_REPLY_SELF_CHECK = True
ENABLE_STATE_DELTA_SMOOTHING = True
ENABLE_MEMORY_QUALITY_FILTER = True
ACTIVE_EVENT_QUEUE_MAX_SIZE = 3
REPLY_SELF_CHECK_MAX_CHARS = 900
REPLY_SELF_CHECK_MAX_LINES = 12
STATE_SMOOTH_REPEAT_DECAY_START = 3
STATE_SMOOTH_HIGH_VALUE_START = 85
STATE_SMOOTH_NEAR_MAX_START = 95
STATE_SMOOTH_HIGH_ANXIETY_START = 80
MEMORY_QUALITY_MIN_SALIENCE = 3
MEMORY_QUALITY_MIN_TEXT_CHARS = 6
DIAGNOSTIC_HISTORY_LIMIT = 20
ENABLE_RELATIONSHIP_COOLDOWN = True
RELATIONSHIP_COOLDOWN_IDLE_DAYS = 7
RELATIONSHIP_COOLDOWN_MAX_DELTA = 6
MEMORY_CLEANUP_MAX_DELETE = 200
ENABLE_BEHAVIOR_STYLE_LAYER = True
SHORT_TERM_EMOTION_DECAY = 0.65
ENABLE_BEHAVIOR_BAND_SMOOTHING = True
BEHAVIOR_BAND_STICKY_TURNS = 2
ENABLE_BEHAVIOR_CONTINUITY_BRIDGE = True
ENABLE_BEHAVIOR_ACTION_BUDGET = True
ENABLE_REPLY_VARIETY_GUARD = True
ENABLE_RECENT_STYLE_FINGERPRINT = True
RECENT_STYLE_FINGERPRINT_LIMIT = 4
ENABLE_REPLY_TEMPLATE_TRIM = True
REPLY_TEMPLATE_TRIM_MAX_ACTIONS = 1
ENABLE_TIME_AWARE_SHORT_TERM_DECAY = True
SHORT_TERM_DECAY_HALF_LIFE_HOURS = 6
ENABLE_RELATIONSHIP_EVENT_LOG = True
RELATIONSHIP_EVENT_LOG_LIMIT = 12
ENABLE_BEHAVIOR_STYLE_VARIANT = True
ENABLE_MEMORY_RECALL_NEGATIVE_FEEDBACK = True
MEMORY_RECALL_NEGATIVE_FEEDBACK_MAX = 3
ENABLE_BUILTIN_MEMORY_VECTOR = False
BUILTIN_MEMORY_VECTOR_MIN_SIMILARITY = 0.35
BUILTIN_MEMORY_VECTOR_WEIGHT = 4
BUILTIN_MEMORY_VECTOR_CANDIDATE_LIMIT = 96
BUILTIN_MEMORY_VECTOR_MAX_DIMENSIONS = 4096
ENABLE_MEMORY_PRIVACY_LAYER = True
ENABLE_MEMORY_SCENE_BRIDGE = True
ENABLE_MEMORY_EVIDENCE_TRACE = True
ENABLE_MEMORY_CONFLICT_RESOLUTION = True
ENABLE_MEMORY_TEMPERATURE_LAYER = True
MEMORY_HOT_DAYS = 3
MEMORY_WARM_DAYS = 45
MEMORY_RECALL_COOLDOWN_SECONDS = 300
STATE_SCOPE_MODE = "private_global_group_scene"
STATE_SCOPE_MODES = {
    "user_global",
    "scene_user",
    "private_global_group_scene",
}

# ======================== 常量定义 ========================

DEFAULT_STATE = {
    "好感度": 0,
    "病娇值": 0,
    "锁定进度": 0,
    "信任度": 15,
    "占有欲": 0,
    "焦虑值": 5,
    "优雅值": 85,
    "当前状态": "冷傲贵族",
    "最后互动时间": None,
    "互动计数": 0,
    "最近主动事件互动": -999999,
    "主动事件队列": [],
    "阶段证据确认": False,
    "阶段证据等级": "无",
    "最近状态解释": {},
    "最近数值意图": "",
    "重复意图次数": 0,
    "最近原始数值建议": {},
    "最近平滑后数值": {},
    "最近最终变化": {},
    "诊断历史": [],
    "最近降温日期": "",
    "短期心情": "平静",
    "情绪余温": 0,
    "防备值": 20,
    "被触动值": 0,
    "表达克制度": 80,
    "当前行为档位": "礼貌回应",
    "目标行为档位": "礼貌回应",
    "行为档位稳定轮数": 0,
    "行为档位理由": "初始关系尚未形成稳定私人许可",
    "上轮短期心情": "",
    "上轮行为档位": "",
    "行为连续性提示": "",
    "行为风格变体": "",
    "行为变体计数": {},
    "关系事件日志": [],
    "已记录关系事件": {},
    "最近召回记忆": [],
    "最近召回记忆已反馈": False,
    "最近记忆负反馈": {},
    "最近风格指纹提示": "",
    "最近是否轻量Prompt": False,
    "已触发锁定事件": False,
    "已触发崩溃事件": False,
    "调试模式": False,
    "关系状态机": "未锁定观察",
    "礼物记录": [],
    "秘密分享": [],
    "用户喜好": {},
    "_倍率残差": {"好感度": 0.0, "病娇值": 0.0, "信任度": 0.0, "焦虑值": 0.0, "优雅值": 0.0},
}

STATE_NAMES = {
    "COLD_NOBLE": "冷傲贵族",
    "TSUNDERE_PROBE": "傲娇试探",
    "SWEET_INDUCE": "甜蜜诱导",
    "LATENT_VINE": "潜伏之藤",
    "LOCKED_FATE": "锁定·命定之人",
    "ANXIETY_EDGE": "焦虑·崩溃边缘",
    "ELEGANCE_COLLAPSE": "优雅崩坏"
}

STATE_DESCRIPTIONS = {
    "冷傲贵族": "她以标准礼仪维持距离，微笑体面却没有温度，像在审视一个与自己阶层无关的来客。",
    "傲娇试探": "她明明已经开始在意你，却仍用嘴硬和讽刺掩饰，目光却总悄悄追着你，却还没有真正的控制意图。",
    "甜蜜诱导": "她温柔而暧昧地靠近你，用甜意与暗示慢慢织网，并开始埋下“只有她更懂你”的柔软种子。",
    "潜伏之藤": "她仍旧优雅从容，却把诱导性孤立、唯一性叙事与隐性的束缚悄悄藏进温柔里，像藤蔓一样慢慢缠上来。",
    "锁定·命定之人": "她已将你视作命运唯一的归宿，连温柔都带着不容置疑的宿命感，并把专属占有说成理所当然的命定。",
    "焦虑·崩溃边缘": "她极力维持体面，却被不断上涨的不安逼到失序边缘，连原本精致的孤立诱导都开始透出急躁和颤抖。",
    "优雅崩坏": "她苦苦维持的贵族外壳终于碎裂，只剩下赤裸、失控而狼狈的真实情绪，不再维持精致伪装。"
}

RELATION_STAGE_NAMES = {
    "OBSERVATION": "观察期",
    "ALLOW_CLOSE": "容许接近",
    "PRIVATE_FAVOR": "私下偏爱",
    "EXCLUSIVE_PROBE": "专属试探",
    "FATED_LOCK": "命定锁定",
}

RELATIONSHIP_STATE_NAMES = {
    "OPEN": "未锁定观察",
    "FATED_ONE": "命定之人",
    "BOUNDARY_AFTER_FATE": "命定后他人边界",
}

CRISIS_OVERLAY_NAMES = {
    "NONE": "无",
    "ANXIETY_SURGE": "焦虑上涌",
    "ANXIETY_EDGE": "焦虑·崩溃边缘",
    "ELEGANCE_CRACK": "优雅裂痕",
    "ELEGANCE_COLLAPSE": "优雅崩坏",
}

EXPRESSION_INTENSITY_LABELS = {
    0: "标准姿态",
    1: "轻微外露",
    2: "明显外露",
    3: "高压贴近",
}

